### ISSUE TITLE
อยากรบกวนขอไฟล์ geojson หน่อยครับ

### ISSUE THREAD

**Issue by edwardmelody** [KittapatR/Thai-ECT-election-map-66#2]
ถ้าไม่รบกวนมากอาจจะใช้ Google drive ก็ได้ครับ ดูแล้วน่าจะติดเรื่อง GitHub purchasing ไม่สามารถดาวโหลดไฟล์ที่เป็น LFS ได้ครับผม

**Comment by KittapatR** [comment]
First of all, thank you @edwardmelody for your interest in my repo!

Here is the link you requested:
https://drive.google.com/drive/folders/1tVIGxPkNb7Yysz2kjiANIkG7hTFQNjtq

The files you requested will be all uploaded approx. 8 PM Today.
